### PR TITLE
Addressed issue #61 by placing a conditional on a deprecated warning.

### PR DESCRIPTION
**Pull request by BillCleveland-USRA**
Added a conditional to model's init to make it compatible with Numpy 2.0.0 and later.

### CODE REVIEW

**Comment by BillCleveland-USRA** [comment]
Why do we disable the deprecation warnings?

**Comment by AdamGoldstein-USRA** [comment]
That's a good question.

**Comment by AdamGoldstein-USRA** [comment]
It would probably be better to not ignore the warning and run the unit tests to see if it raises any warning.

**Comment by BillCleveland-USRA** [comment]
We could close this pull request without merge, and submit a new one that removes the ignore functions.

**Comment by AdamGoldstein-USRA** [comment]
That's true, although it looks like PR #71 contains a different fix for this.

**Comment by AdamGoldstein-USRA** [comment]
Addressed in PR #71 for now. May consider removing the warning filter completely, but we should test to make sure there is no reason to have it.

**Pull request closed without merging**
